services:
  app:
    build: .
    image: insta-post-to-pdf:latest
    container_name: insta-post-to-pdf
    restart: unless-stopped
    ports:
      - "127.0.0.1:8585:8585"
    command: uvicorn app:app --host 0.0.0.0 --port 8585
    volumes:
      - download_data:/app/download
      - logs_data:/app/logs

volumes:
  download_data:
  logs_data: